use_frameworks!

target 'KikBank_Example' do

  pod 'KikBank', :path => '../'
  pod 'RxCocoa', '~> 4.0'

  target 'KikBank_Tests' do
    inherit! :search_paths
    pod 'KikBank', :path => '../'
  end
end
